services:
  mariadb:
    container_name: flibusta-to-postgres-db-mariadb
    env_file:
    - environment.env
    image: mariadb
  postgres:
    container_name: flibusta-to-postgres-db-postgres
    env_file:
    - environment.env
    volumes:
    - "./volumes/postgres-init:/docker-entrypoint-initdb.d/"
    - ./backup:/backup
    image: postgres:alpine
  converter:
    container_name: converter
    build:
      dockerfile: Dockerfile
    env_file:
    - environment.env
    volumes:
    - ./backup:/backup
    - ./dump/:/dump
    environment:
    - WAIT_HOSTS=mariadb:3306,postgres:5432
    - WAIT_HOSTS_TIMEOUT=300
    - WAIT_SLEEP_INTERVAL=3

